### ISSUE TITLE
Initial tasks & questions

### ISSUE THREAD

**Issue by aspino** [learningtapestry/lcms-engine#1]
After taking a 'moderate' look into the Odell and Unbounded LCMS codebases, I'd like to share a list of things that I think should be addressed and agreed upon before starting work on the core engine. 

Let's discuss if these are valid points or not. Perhaps some of them are not needed, too costly, can be done in a better way, etc.    

- Base project on Odell LCMS since codebase is a bit cleaner and uses more modern versions of dependencies. Can we also extract some common assets from Odell UI, or is that project 100% exclusive to Odell, as its name suggests?
- Start with administration panel, because it's where features are most similar.
- Provide default/minimal styles for non-admin section. Or none at all?... both Odell & Unbounded seem to differ a lot visually and in structure, so they'll override the default styles anyway.
- Try to make the engine compatible with ruby 2.3, 2.4 and 2.5. Current version in apps is 2.3.3. We should update at least to the latest point release.
- Try to make engine compatible with rails 4.2 initially, and up to rails 5.2, so it will be ready when apps are updated.
- Move all JS assets to Webpack. Should we move stylesheets, images, etc. as well?
- Webpacker is not compatible with engines yet (see https://github.com/rails/webpacker/issues/348), so we can not rely on the engine to provide the assets in an easy & supported way. Without considering more creative or hacky ideas, we've got some options, though:
  - If we want to stick with Webpacker, then we can just configure the JS assets in every application and not in the engine. It's the simplest choice but also kind of defeats the purpose of creating an engine to share resources.
  - Forget about Webpacker until engine support is added, and stick with Sprockets to import the JS resources from the engine.
  - Move all JS files, although this could also include all kinds of static assets, to NPM packages and only use the engine gem for ruby code. Overall, I think this would be my preferred option, as it seems cleaner and more future-proof.
  - I see you're already applying some kind of workaround (https://github.com/learningtapestry/odell-ui/wiki/Details-on-Webpacker-integration) in odell-ui in order to solve this problem. I guess it's a solution worth considering, specially if you're already using it. However, it still forces you to duplicate dependencies in both engine and application, and blurs a bit the line separating them, which is not ideal from an architectural point of view.

**Comment by paranoicsan** [comment]
Closing this as outdated
