### ISSUE TITLE
Research way to `set(wait: DELAY)` for jobs

### ISSUE THREAD

**Issue by shlag3n** [learningtapestry/lcms-engine#105]
- [ ] 1. Check if it'll work out of the box as suppose to, but more likely we need to set up smth additional for resque https://github.com/resque/resque/issues/1313.
- [ ] 2. Add workaround

source: https://github.com/learningtapestry/openscied-lcms/issues/130

**Comment by paranoicsan** [comment]
It seems the easiest way will be to get rid of _resque_ gem and move to something else.
