### ISSUE TITLE
Add `strict_loading` instead of bullet gem

### ISSUE THREAD

**Issue by paranoicsan** [learningtapestry/lcms-engine#151]
As of Rails 6.1 there is [possibility](https://github.com/rails/rails/pull/37400) to catch queries which lead to N+1 queries, we might need to remove bullet gem from the project and replace model calls with `strict_loading` options.

**Comment by aderyabin** [comment]
I'm not sure we can compare `bullet` and `strict_loading`.
`bullet` gem is a monitoring tool for a [black box](https://en.wikipedia.org/wiki/Black-box_testing) to find `n+1` queries.
`strict_loading` is a developer control.

**Comment by paranoicsan** [comment]
Fair enough. Closing this.
